In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/home/catpc/machine lerarning/CAR DETAILS FROM CAR DEKHO.csv',usecols=['name','fuel','seller_type','transmission','owner'])

df.head()

name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner

# To summarize 

Ordinal varibles --> ordinalEcooder: Owner, seller_type, Transmisson
Target or label variables --> LabelEncoder: fuel


# using python 

In [3]:
df.drop('name',axis=1, inplace=True)

In [4]:
df.head()

fuel seller_type transmission         owner
0  Petrol  Individual       Manual   First Owner
1  Petrol  Individual       Manual   First Owner
2  Diesel  Individual       Manual   First Owner
3  Petrol  Individual       Manual   First Owner
4  Diesel  Individual       Manual  Second Owner

In [5]:
df['transmission'].value_counts()

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64

In [6]:
#df['transmission'] = df['transmission'].map({'Manual':0, 'Automatic':1})

In [7]:
df.head()

fuel seller_type transmission         owner
0  Petrol  Individual       Manual   First Owner
1  Petrol  Individual       Manual   First Owner
2  Diesel  Individual       Manual   First Owner
3  Petrol  Individual       Manual   First Owner
4  Diesel  Individual       Manual  Second Owner

In [8]:
df['seller_type'].value_counts()

seller_type
Individual          3244
Dealer               994
Trustmark Dealer     102
Name: count, dtype: int64

In [9]:
#df['seller_type'] = df['seller_type'].map({'Individual':0,'Dealer':1,'Trustmark Dealer': 2})

In [10]:
df.head()

fuel seller_type transmission         owner
0  Petrol  Individual       Manual   First Owner
1  Petrol  Individual       Manual   First Owner
2  Diesel  Individual       Manual   First Owner
3  Petrol  Individual       Manual   First Owner
4  Diesel  Individual       Manual  Second Owner

In [11]:
#df['transmission'].apply(lambda x: 1 if x=='Manual' else 0)

In [12]:
df.head()

fuel seller_type transmission         owner
0  Petrol  Individual       Manual   First Owner
1  Petrol  Individual       Manual   First Owner
2  Diesel  Individual       Manual   First Owner
3  Petrol  Individual       Manual   First Owner
4  Diesel  Individual       Manual  Second Owner

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train,y_test = train_test_split(df.drop('fuel',axis=1),df['fuel'],test_size=0.2, random_state=42)


# single columns -> labelorder
multiple columns-> ordinalencoder

# using Scikitlearn

In [15]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder


# 1 Apply Label Encoder

In [16]:
le = LabelEncoder()

In [17]:
y_train_scaled = le.fit_transform(y_train)
y_test_scaled = le.transform(y_test)

In [18]:
df['fuel'].value_counts()

fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64

In [19]:
y_train_scaled

array([1, 1, 4, ..., 1, 1, 4])

In [20]:
x_train.head()

seller_type transmission         owner
227   Individual       Manual   First Owner
964   Individual       Manual   First Owner
2045  Individual       Manual  Second Owner
1025  Individual       Manual   First Owner
4242      Dealer       Manual   First Owner

# apply ordinal encoder

In [21]:
oe = OrdinalEncoder()
x_train_traf = oe.fit_transform(x_train)
x_test_traf =oe.transform(x_test)

In [22]:
x_train_traf

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 2.],
       ...,
       [0., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

# using pandas onehotecoder

In [29]:
df  = pd.DataFrame([ 
{'buyer':'ali','fruits':'apple','gender':'male','value':2},
    {'buyer':'noor','fruits':'mango','gender':'male','value':3},
    {'buyer':'rohima','fruits':'orange','gender':'female','value':4},
    {'buyer':'karim','fruits':'banana','gender':'male','value':4},
    
])
df

buyer  fruits  gender  value
0     ali   apple    male      2
1    noor   mango    male      3
2  rohima  orange  female      4
3   karim  banana    male      4

In [32]:
pd.get_dummies(data=df, columns=['buyer','fruits','gender'],dtype=int,drop_first='first')


value  buyer_karim  buyer_noor  buyer_rohima  fruits_banana  fruits_mango  \
0      2            0           0             0              0             0   
1      3            0           1             0              0             1   
2      4            0           0             1              0             0   
3      4            1           0             0              1             0   

   fruits_orange  gender_male  
0              0            1  
1              0            1  
2              1            0  
3              0            1

# with sklearn OneHotEncoder
when sparse=True , the encoded output is returned as a sparse matrix , while sparse=False a dense matrix

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [35]:
ohe = OneHotEncoder(drop='first',dtype=int,sparse_output=False)

In [37]:
df_trf = ohe.fit_transform(df[['buyer', 'fruits', 'gender']])  # ডাবল ব্র্যাকেট ব্যবহার করুন

In [38]:
df_trf

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1]])

In [44]:
cols = ohe.get_feature_names_out()
cols


array(['buyer_karim', 'buyer_noor', 'buyer_rohima', 'fruits_banana',
       'fruits_mango', 'fruits_orange', 'gender_male'], dtype=object)

In [45]:
df_trf

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1]])

In [46]:
pd.DataFrame(data=df_trf,columns=cols)

buyer_karim  buyer_noor  buyer_rohima  fruits_banana  fruits_mango  \
0            0           0             0              0             0   
1            0           1             0              0             1   
2            0           0             1              0             0   
3            1           0             0              1             0   

   fruits_orange  gender_male  
0              0            1  
1              0            1  
2              1            0  
3              0            1