In [1]:
import numpy as np

In [2]:
import pandas as pd


In [3]:
df = pd.read_csv('/home/catpc/Downloads/9 covid_toy.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [6]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [7]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

# Train test split

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']


In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
x_train.shape, y_train.shape, x_test.shape,y_test.shape

((80, 5), (80,), (20, 5), (20,))

# 1 without column Transformer

# missing values fill

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
x_train.head()

age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [23]:
simple = SimpleImputer()
x_train_fever = simple.fit_transform(x_train[['fever']])

x_test_fever = simple.fit_transform(x_test[['fever']])

In [25]:
x_train_fever.shape,x_test_fever.shape

((80, 1), (20, 1))

# encoding categorical values

In [26]:
from sklearn.preprocessing import OrdinalEncoder 

In [35]:
ordinal = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = ordinal.fit_transform(x_train[['cough']])
x_test_cough = ordinal.fit_transform(x_test[['cough']])

In [37]:
x_train_cough.shape, x_test_cough.shape

((80, 1), (20, 1))

In [52]:
#gender and city 
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')


In [58]:
x_train.head()

age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [59]:
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [61]:
#Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

In [62]:
x_train_age

array([[81],
       [ 5],
       [19],
       [27],
       [73],
       [70],
       [49],
       [51],
       [64],
       [83],
       [65],
       [18],
       [16],
       [16],
       [27],
       [84],
       [51],
       [69],
       [82],
       [69],
       [44],
       [74],
       [20],
       [12],
       [33],
       [42],
       [65],
       [23],
       [56],
       [64],
       [13],
       [31],
       [40],
       [49],
       [19],
       [11],
       [14],
       [42],
       [38],
       [46],
       [71],
       [10],
       [60],
       [22],
       [19],
       [65],
       [19],
       [54],
       [81],
       [20],
       [48],
       [82],
       [23],
       [66],
       [ 5],
       [49],
       [ 5],
       [34],
       [79],
       [ 6],
       [10],
       [69],
       [55],
       [34],
       [27],
       [47],
       [73],
       [42],
       [80],
       [47],
       [38],
       [34],
       [25],
       [24],
       [12],
       [24],
       [75],

In [63]:
#also the test data 
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

In [64]:
x_test_age

array([[17],
       [83],
       [68],
       [72],
       [20],
       [50],
       [71],
       [14],
       [75],
       [60],
       [64],
       [15],
       [34],
       [26],
       [59],
       [65],
       [80],
       [ 8],
       [25],
       [83]])

In [67]:
x_train_transformed = np.concatenate(
    (x_train_age, x_train_fever, x_train_gender_city, x_train_cough),
    axis=1
)

x_train_transformed

array([[ 81., 101.,   0.,   0.,   0.,   1.,   0.],
       [  5., 100.,   0.,   0.,   1.,   0.,   0.],
       [ 19., 100.,   0.,   0.,   1.,   0.,   0.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 73., 103.,   0.,   1.,   0.,   0.,   0.],
       [ 70., 103.,   1.,   0.,   1.,   0.,   1.],
       [ 49., 102.,   0.,   1.,   0.,   0.,   0.],
       [ 51., 101.,   0.,   0.,   1.,   0.,   1.],
       [ 64., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 83., 101.,   0.,   0.,   1.,   0.,   0.],
       [ 65.,  98.,   0.,   0.,   0.,   1.,   0.],
       [ 18., 104.,   0.,   0.,   0.,   0.,   0.],
       [ 16., 103.,   0.,   0.,   0.,   0.,   0.],
       [ 16., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 27., 100.,   1.,   0.,   1.,   0.,   0.],
       [ 84., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 51., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 69., 102.,   0.,   0.,   0.,   0.,   0.],
       [ 82., 102.,   0.,   0.,   0.,   0.,   1.],
       [ 69., 103.,   0.,   0.,

In [68]:
x_train_transformed.shape

(80, 7)

# 2 with column transformer

In [75]:
x_train.head()


age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [76]:
from sklearn.compose import ColumnTransformer

In [80]:
tf = ColumnTransformer(
transformers=[
    ("tf1",SimpleImputer(),['fever']),
    ('tf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tf3',OneHotEncoder(drop='first',sparse_output=False, handle_unknown='ignore'),['gender','city']),
],
    remainder = 'passthrough'
    
)

In [81]:
x_train_tf = tf.fit_transform(x_train)
x_test_tf = tf.fit_transform(x_test)

In [98]:
x_train_tf_df = pd.DataFrame(data = x_train_tf, columns = ['age', 'gender', 'fever', 'cough', 'city', 'some_col6', 'some_col7']
)


In [100]:
x_train_tf_df



age  gender  fever  cough  city  some_col6  some_col7
0   101.0     0.0    0.0    0.0   0.0        1.0       81.0
1   100.0     0.0    0.0    0.0   1.0        0.0        5.0
2   100.0     0.0    0.0    0.0   1.0        0.0       19.0
3   100.0     0.0    1.0    1.0   0.0        0.0       27.0
4   103.0     0.0    0.0    1.0   0.0        0.0       73.0
..    ...     ...    ...    ...   ...        ...        ...
75  102.0     1.0    0.0    0.0   0.0        0.0       24.0
76  104.0     1.0    0.0    1.0   0.0        0.0       75.0
77  104.0     0.0    1.0    0.0   0.0        0.0       51.0
78  102.0     1.0    0.0    0.0   1.0        0.0       82.0
79  100.0     1.0    0.0    0.0   1.0        0.0       11.0

[80 rows x 7 columns]